### ISSUE TITLE
Question: How can we use this code in MS Visual Studio?

### ISSUE THREAD

**Issue by RmanSC** [JamesBremner/in2out#10]
James,
Is there a way to use this code and build it in MS Visual Studio?
I'm asking, because we want to make text input, dropboxes and etc. for some parameters, that will be calculated in process.cpp.

We want our internal users to operate the app not from cmd, but open it, enter required parameters, including port and ip, and then just click the button to start data receiving and transfer 

Regards,
Arman

**Comment by RmanSC** [comment]
Sorry, if I used label incorrectly. This issue should not be considered as new feature request, but as question only.

**Comment by JamesBremner** [comment]
Why did you not specify that you wanted a GUI initially?

My standard socket wrapper works very well in a GUI.  I had to write a `new` wrapper to make things work in a console program!

It is a trivial task to replace the console socket wrapper with the one for use in a GUI, then add whatever widgets you need.

**Comment by RmanSC** [comment]
James,
No worries. Console app is exactly, what we wanted for this iteration. Once we test it with modified process.ccp, we will make another iteration with GUI. If you are willing to, we will be glad to involve you on that scope.

Thanks for answering.

Regards,
Arman
