### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/in2out#3]
We have a new concept called a **_package_**

It is required to modify the last line only of each package ( see #1 )

We need to determine the end of a package, unambiguously.

**Comment by RmanSC** [comment]
By package I mean data package, that will be send periodically through certain port. It will end with /n, as was discussed in the email.
In reality, every time package will increase by one line, that will end with /n, but due to limited access to the machine with actual software, we simulate this data package with message as attached.
[21082022 message to sent.txt](https://github.com/JamesBremner/in2out/files/9388946/21082022.message.to.sent.txt)

**Comment by JamesBremner** [comment]
Thank you for finally responding.

Every line ends with a \n.  I need to know what makes a package different from a line.

**Comment by JamesBremner** [comment]
It looks to me like your "package" begins with

`"Time\tTR PRESS\tAN PRESS\tSLUR RATE\r\n`

Is this correct?

If so, then we can identify the end of a package when we receive this.

**Comment by RmanSC** [comment]
Yes, it's correct. It should be noted, that this "header" will change from one session to another, meaning, that once you open program next time, "header can be different"

**Comment by JamesBremner** [comment]
Could you please post a complete description of a "package"  In particular, describe the headers that mark the beginning of a new package and how they change.

**Comment by RmanSC** [comment]
Session from the machine with licensed program (which we cannot test on right now) will start with defining which parameters (they are changing dynamically) to send via port. After parameters, period of time for sending and port are defined, it will start to create package of data, that will be sent periodically to defined socket. Every period package will increase by one line of actual values of parameters, that were defined before.
Package is a data set, that will start with "header", that contain names of defined parameters and then on next line package will continue with past and actual values of parameters, delimited by tab. Every period will be delimited by /n, last line will end with /n. Number of parameters are fixed for every session, but with new session can be different.

I hope, it's more clear now.

**Comment by JamesBremner** [comment]
So:

```
LINE: A line is a sequence of ascii characters terminated with '\n' character

PACKAGE: A package is a sequence of lines of unknown number.

HEADER: The first line of a package does NOT contain an initial valid datestamp

DATA: Every line except the first in a package contains an initial valid datestamp

NOTE: There is no way to distinguish the last line of a package ( It is an ordinary data line )
```

Is this correct?

**Comment by RmanSC** [comment]
Yes, everything is correct. Thanks for defining it laconically

**Comment by JamesBremner** [comment]
The lack of a terminator for your package makes handling it very difficult.  Who designed this?

The only way to know if the last line has been received is to wait for the header of the next package to arrive.

Do you want to add a new feature to in2out: package handling?

**Comment by JamesBremner** [comment]
from an email: "If it's too hard, then let's close it. If you know the way to do it, I will be glad to offer you additional 100 USD to compensate your efforts."

That sounds as if it might be a _yes_

Package handling:

- framecheck does not output the last data line received.  It holds on to it until the next line arrives.  If the next line is another data line then the previous is output. If the next line is a package header, then the last line is sent to be modified, then output.  Then the header line is output.

Option:  I would like to fix the horrible design error by outputting a package termination line ( "package_end\n" before the package header.  This may confuse whatever is receiving the data if it is not expecting this, but if possible this would make everything much easier downstream. Let me know.

**Comment by RmanSC** [comment]
James,
It will be great feature. Please, do it.

**Comment by JamesBremner** [comment]
Do you want the optional package terminator?

**Comment by RmanSC** [comment]
Do you mean from package generator side or from in2out.exe side?
If from in2out.exe side, then yes. We cannot change package generator app unfortunately.

**Comment by JamesBremner** [comment]
Package handling:

framecheck does not output the last data line received. It holds on to it until the next line arrives. 

If the next line is another data line then the previous is output.

If the next line is a package header, then the last line is sent to be modified, then output.  Then a package termination line is output ( "package_end\n" )  Then the header line is output.

This will be in2out v1.4

**Comment by JamesBremner** [comment]
I am ready to proceed on this feature.  Just waiting for you to deposit the SafePay funds.

**Comment by RmanSC** [comment]
It's fixed

**Comment by JamesBremner** [comment]
When I send the following to in2out v1.4

`"07/04/2016 Data1\n07/04/2016 Data2\n07/04/2016 Data3\nHeader\n"`

The console displays

```
Input: 07/04/2016 Data1
07/04/2016 Data2
07/04/2016 Data3
Header

Input Hex: 30 37 2f 30 34 2f 32 30 31 36 20 44 61 74 61 31 a 30 37 2f 30 34 2f 32 30 31 36 20 44 61 74 61 32 a 30 37 2f 30 34 2f 32 30 31 36 20 44 61 74 61 33 a 48 65 61 64 65 72 a

Package end
wex::tcp::send Header
wex::tcp::send 07/04/2016 Data1
wex::tcp::send 07/04/2016 Data2
wex::tcp::send 07/04/2016 Data3 modified
wex::tcp::send package_end
```

**Comment by RmanSC** [comment]
Package end is identified prematurely in current version.

As it was hard to figure out for me how package_end was identified, I deleted line 118 with InputDisplay function.
[22082022 attemp 2.txt](https://github.com/JamesBremner/in2out/files/9395346/22082022.attemp.2.txt)
As you can see on line

wex::tcp::send 07/04/2016 11:39:37      1       1       0.0 modified
wex::tcp::send package_end

It shows, that package was ended, however it was not and contunued after:

wex::tcp::send 0☺рМ═█7/04/2016 11:39:38 1       1       0.0
wex::tcp::send 07/04/2016 11:39:39      1       1       0.0
wex::tcp::send 07/04/2016 11:39:40      1       1       0.0

"☺рМ═█" cannot be a trigger as you can find it in other lines, that was not identified as package_end.

See below other test without deleting InputDisplay in the code.

[22082022 attemp 1.txt](https://github.com/JamesBremner/in2out/files/9395373/22082022.attemp.1.txt)

**Comment by JamesBremner** [comment]
When you submit an unsuccessful test report, please remember to assign the issue back to me.

The package handler was confused by the unexpected 2nd header ( #8 ).  Please retest in v1.4.1

To be clear, this issue is still assigned to you in test.

**Comment by JamesBremner** [comment]
Please retest in v1.4.3

**Comment by RmanSC** [comment]
Hello,
I tested again new version with deleting InputDisplay.  Package for the test.
[21082022 message to sent.txt](https://github.com/JamesBremner/in2out/files/9403997/21082022.message.to.sent.txt)

It still throw package_end at the middle of the package.
[230822 attemp 1.txt](https://github.com/JamesBremner/in2out/files/9403991/230822.attemp.1.txt)

However, when I loaded file again in packet sender app, this issue didn't occur.
[230822 attemp 2.txt](https://github.com/JamesBremner/in2out/files/9403994/230822.attemp.2.txt)
 
Not sure, what could happen.

Is it suppose to work as in attempt 1 file?

**Comment by JamesBremner** [comment]
Here are the first 3 lines of the message in21082022 message to sent.tx
```
"Time\tTR PRESS\tAN PRESS\tSLUR RATE\r\n
mm/dd/yyyy hh:mm:ss\tpsi\tpsi\tbbl/min\r\n
____\t________\t________\t_________\t\r\n
```

This looks like another, third header line!

v1.4.3 is only expecting two header lines.

First you told me there was one header line.  Then two.

Please specify EXACTLY what the header(s) of the packages look like, once and for all.

**Comment by JamesBremner** [comment]
It seems that you are unable to specify how many headers are present, nor what their format will be.

I will therefore have to invert the test: a header is ANY line that is NOT a data line.

I will also have to check for the FIRST HEADER ( which marks the end of the previous package ) and treat all headers that follow as data lines, until the first real data line of the new package is found.

**Comment by JamesBremner** [comment]
By the way, this is not a bug.  I implemented exactly what you specified.  Please do not label issues as bugs, if they are the result of a specification error.

**Comment by JamesBremner** [comment]
I have updated the input description with the new specification https://github.com/JamesBremner/in2out/wiki/Input

Please review this carefully.  I would really like to stop iterating on these specification changes.

**Comment by JamesBremner** [comment]
After working on this for a while, I realised that identifying the first header is not only difficult, it is beside the point.  The important thing is to identify the last data line of a package.  This is the line we need to modify before sending it.

So: the last data line is a data line followed by a non data line ( which will be the start of the next package, but we don't care about that, nor how many non data lines follow )

**Comment by JamesBremner** [comment]
v1.4.4

**Comment by RmanSC** [comment]
James,
My apologies. My fault on wrong definition initially. 

I tested this version. See below report:

[240822 attemp 1.txt](https://github.com/JamesBremner/in2out/files/9416834/240822.attemp.1.txt)

I think, we can close this project.

Regards,
Arman
