### ISSUE TITLE
Input data waits for server connection

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/in2out#5]
In v1.2 data that arrives when the listener is disconnected is discarded.

Now that the in2out application no longer searches continually for the server's return, but instead only checks for the server when new data arrives, data that arrives when the server is back up but not yet connected will also be discarded.

This seems unsatisfactory to me.

In v1.3 data that arrives when there is no listener connected is not discarded, but saved, waiting for the listener to be reconnected.  When the listener is reconnected and new data arrives, the waiting data is send, followed by the new data.

The snag is that if the listener is disconnected for a long time and data continues to pour in then the waiting buffer becomes very long and the data in it may well be stale ( no longer of any significance ).  So I have added a new keyboard command: `flush`  If the user types this on the in2out console, any data in the waiting buffer will be discarded.

**Comment by JamesBremner** [comment]
v1.3

**Comment by RmanSC** [comment]
James,
Thanks for your input. It worked good, it's good feature, but probably we will go with 1.2 version.
