### ISSUE TITLE
After listener connect failure, instrumentation shows wrong port number

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/in2out#6]
The next connection attempt still uses the correct port.

Reported in #4

**Comment by JamesBremner** [comment]
The port number is showing in hexadecimal - left over from showing input in hex.

I will set the output back to decimal, which should fix this.

**Comment by JamesBremner** [comment]
v1.2.1

**Comment by JamesBremner** [comment]
Reminder:  This was assigned to you 6 says ago.  Waiting for a test report.

**Comment by RmanSC** [comment]
It's fixed
