### ISSUE TITLE
Handle unexpected header

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/in2out#8]
Reported in #7

This is unexpected

`mm/dd/yyyy hh:mm:ss     psi     psi     bbl/min`

**Comment by JamesBremner** [comment]
Updated input description https://github.com/JamesBremner/in2out/wiki/Input

**Comment by JamesBremner** [comment]
v1.4.1

**Comment by JamesBremner** [comment]
Please test in v1.4.3

**Comment by RmanSC** [comment]
James, I'm not sure, what this issue is about.
If it's about, that there are more than 1 line, that have letters in the package, then I can say, that with current version issue is closed and multiple lines with letters are handled correctly, as expected from the app.

**Comment by JamesBremner** [comment]
I think we can sort out all these unexpected headers in #3
